AP_Math: allow fabs when HAL_WITH_POSTYPE_DOUBLE
  ../../libraries/AC_PrecLand/AC_PrecLand_StateMachine.cpp: In member function 'AC_PrecLand_StateMachine::Status AC_PrecLand_StateMachine::retry_landing(Vector3p&)':
  ../../libraries/AP_HAL/AP_HAL_Macros.h:50:17: error: 'DO_NOT_USE_DOUBLE_MATHS' was not declared in this scope
     50 | #define fabs(x) DO_NOT_USE_DOUBLE_MATHS()
        |                 ^~~~~~~~~~~~~~~~~~~~~~~
  ../../libraries/AP_Math/control.h:12:15: note: in expansion of macro 'fabs'
     12 | #define fabsP fabs
        |               ^~~~
  ../../libraries/AC_PrecLand/AC_PrecLand_StateMachine.cpp:219:13: note: in expansion of macro 'fabsP'
    219 |         if (fabsP(pos.z - retry_pos_m.z) < MAX_POS_ERROR_M) {
        |             ^~~~~
  compilation terminated due to -Wfatal-errors.