AP_Logger: initialise last_file value
../../libraries/AP_Logger/AP_Logger_Block.cpp: In member function ‘void AP_Logger_Block::validate_log_structure()’:
../../libraries/AP_Logger/AP_Logger_Block.cpp:282:16: error: ‘last_file’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
         } else if (last_file < next_file) {
                ^~
compilation terminated due to -Wfatal-errors.
cc1plus: some warnings being treated as errors