AP_Logger: correct coverage compilation
Fixes:

[1103/1501] Compiling libraries/SITL/SIM_Parachute.cpp
In file included from ../../libraries/AP_HAL/utility/sparse-endian.h:28,
                 from ../../libraries/AP_RCProtocol/AP_RCProtocol_Backend.h:24,
                 from ../../libraries/AP_RCProtocol/AP_RCProtocol.h:316,
                 from ../../libraries/AP_Logger/AP_Logger.h:16,
                 from ../../libraries/SITL/SIM_FlightAxis.cpp:33:
../../libraries/AP_Common/missing/byteswap.h:9:24: error: redefinition of ‘uint16_t __bswap_16(uint16_t)’
    9 | static inline uint16_t __bswap_16(uint16_t u)
      |                        ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.

In file included from ../../libraries/AP_HAL/utility/sparse-endian.h:28,
                 from ../../libraries/AP_RCProtocol/AP_RCProtocol_Backend.h:24,
                 from ../../libraries/AP_RCProtocol/AP_RCProtocol.h:316,
                 from ../../libraries/AP_Logger/AP_Logger.h:16,
                 from ../../libraries/SITL/SIM_JSON.cpp:30:
../../libraries/AP_Common/missing/byteswap.h:9:24: error: redefinition of ‘uint16_t __bswap_16(uint16_t)’
    9 | static inline uint16_t __bswap_16(uint16_t u)
      |                        ^~~~~~~~~~
compilation terminated due to -Wfatal-errors.