AP_Scripting: correct compilation when !AP_SCRIPTING_BINDING_VEHICLE_ENABLED
Fixes:

../../libraries/AP_Scripting/lua_bindings.cpp: In function 'int lua_AP_Vehicle_set_target_velocity_NED(lua_State*)':
../../libraries/AP_Scripting/lua_bindings.cpp:1240:23: error: 'check_AP_Vehicle' was not declared in this scope; did you mean 'check_AC_Fence'?
 1240 |     AP_Vehicle * ud = check_AP_Vehicle(L);
      |                       ^~~~~~~~~~~~~~~~
      |                       check_AC_Fence
compilation terminated due to -Wfatal-errors.