AP_HAL_ChibiOS: do not build QuickTune on peripherals
kills heavy peripherals

../../libraries/AP_Quicktune/AP_Quicktune.cpp: In member function 'void AP_Quicktune::update(bool)':
../../libraries/AP_Quicktune/AP_Quicktune.cpp:177:32: error: 'vehicle' is not a member of 'AP'
  177 |     const auto &vehicle = *AP::vehicle();
      |                                ^~~~~~~
compilation terminated due to -Wfatal-errors.

[ 688/1225] Compiling libraries/AP_TemperatureSensor/AP_TemperatureSensor_TSYS03.cpp
Waf: Leaving directory `/home/pbarker/rc/ardupilot/build/CubeOrange-periph-heavy'