Sub: correct build when rangefinder not anabled
../../ArduSub/sensors.cpp: In member function 'void Sub::read_rangefinder()':
../../ArduSub/sensors.cpp:80:23: error: 'struct Sub::<unnamed>' has no member named 'alt_cm'
   80 |     rangefinder_state.alt_cm = 0;
      |                       ^~~~~~
compilation terminated due to -Wfatal-errors.