libraries/AP_DroneCAN/AP_DroneCAN.cpp: compile error
./waf configure
./waf rover

[...]

../../libraries/AP_DroneCAN/AP_DroneCAN.cpp: In member function ‘virtual void AP_DroneCAN::init(uint8_t, bool)’:
../../libraries/AP_DroneCAN/AP_DroneCAN.cpp:186:6: error: ‘%u’ directive output may be truncated writing between 1 and 10 bytes into a region of size 4 [-Werror=format-truncation=]
 void AP_DroneCAN::init(uint8_t driver_index, bool enable_filters)
      ^~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: some warnings being treated as errors

Waf: Leaving directory `/home/carsten/devel/ardupilot_master/build/sitl'
Build failed
 -> task in 'objs/AP_DroneCAN' failed (exit status 1):
        {task 140641825613080: cxx AP_DroneCAN.cpp -> AP_DroneCAN.cpp.0.o}
 (run with -v to display more information)

Solution: check return value of snprintf()

gcc version 7.5.0 (opensuse leap 15.4)