Tools: Updated ardupilot-ws and dependencies
commit 761b7e9d8d36a366f9e1895c5380f1a40c4f852b
Merge: cba5c659d2 60f9150694
Author: Sanket Sharma <sharma.sanket272@gmail.com>
Date:   Sat Jan 14 01:35:07 2023 +0530

    Merge branch 'patch-8' of https://github.com/snktshrma/ardupilot into patch-8

commit cba5c659d2433cc02572f90b7373034500f8f5b5
Author: Peter Barker <pbarker@barker.dropbear.id.au>
Date:   Thu Jan 12 13:33:15 2023 +1100

    AP_HAL_ChibiOS: ignore array bounds check while checking 0x0 for writes

    Fixes compiler error on g++ 12

    ../../libraries/AP_HAL_ChibiOS/Scheduler.cpp:568:20: error: array subscript 0 is outside array bounds of 'const uint8_t [0]' [-Werror=array-bounds]
      568 |         if (addr0[i] != 0) {

commit b08eb33978f097ca629e6883076167beb1f88f8b
Author: Peter Barker <pbarker@barker.dropbear.id.au>
Date:   Thu Jan 12 13:02:30 2023 +1100

    Copter: remove FS_OPTIONS parameter conversion

    This code is in 4.0.7 but not 3.6.11 - i.e. after this someone upgrading from 3.6 to master (and presumably 4.4) won't get this conversion done.

    This conversion is flawed in that someone configuring a default for a parameter in a configuration file will have that value over-ridden by this code.

commit 973a7ddde1466254205516c541522834a6e21f5a
Author: Peter Barker <pbarker@barker.dropbear.id.au>
Date:   Thu Jan 12 09:43:32 2023 +1100

    Tools: param_parse.py: sort SIM_ parameters into the output files

    primarily to make the Wiki look nicer

commit 94ea93df489165a4ea37881fbb82c6429fc29154
Author: Peter Barker <pbarker@barker.dropbear.id.au>
Date:   Tue Jan 3 21:19:00 2023 +1100

    AP_AHRS: create an AP_AHRS_SIM backend

commit 5144bdcb12d2cf93f9e907f3ffbc646875882c2b
Author: Henry Wurzburg <hwurzburg@yahoo.com>
Date:   Tue Jan 10 11:28:44 2023 -0600

    SITL: add SITL param metadata and fix a few

commit b8e954a889f62df2ffffb4efcdeeaf5a66c895ac
Author: Peter Barker <pbarker@barker.dropbear.id.au>
Date:   Tue Jan 3 16:54:17 2023 +1100

    AP_HAL_ChibiOS: disable batch sampler on SkyViper-v2450

    saves ~1.8kB

commit 0e35bc8daca33f26aa62da4a9a4547fd563d0183
Author: Peter Barker <pbarker@barker.dropbear.id.au>
Date:   Tue Jan 3 16:51:51 2023 +1100

    AP_InertialSensor: create explicit define for AP_INERTIALSENSOR_BATCHSAMPLER_ENABLED

    this allows the batch sampler to be removed for size reasons, or because you don't have logging enabled

commit 008db9403d4020b608df78d24822911af949fc95
Author: Andy Piper <github@andypiper.com>
Date:   Mon Jan 9 16:33:49 2023 +0000

    AP_Motors: use _dt instead of loop rate for throttle slew calculation

commit c0f4843cd0323cea4056fe0941bb693c7b758f56
Author: Andy Piper <github@andypiper.com>
Date:   Sat Jul 16 10:38:12 2022 +0100

    AP_AHRS: add throttle slew to RATE

    log PD scaling values

commit f93e6cf547c8b81fdf0529588ef8fd4ca07662db
Author: Andy Piper <github@andypiper.com>
Date:   Wed May 11 12:37:03 2022 +0100

    AC_AttitudeControl: boost PD on roll and pitch when slew limit is hit

    boost angle P when slew limit is hit
    move to a single parameter for thrust-gain boosting
    add PD scaling support

commit 541bed0996f3ae3fc6cd37850129fa91d933ae19
Author: Andy Piper <github@andypiper.com>
Date:   Sat May 28 16:58:25 2022 +0100

    AC_PID: support PD boosting

commit eb60d93bc9ea438a13017288c5b21a200559cacc
Author: Andy Piper <github@andypiper.com>
Date:   Wed May 11 17:23:22 2022 +0100

    autotest: anti-gravity test using THR_G_BOOST boost

commit a63236b3d8b4f1477ab1d60f465cca22a8f8e401
Author: Andy Piper <github@andypiper.com>
Date:   Wed May 11 10:14:51 2022 +0100

    AP_Motors: calculate throttle slew rate

    use derivative filter and apply filtering to slew detector

commit 82ff54ce5f9e619b78c2c76f62c8425b9d893a42
Author: Andy Piper <github@andypiper.com>
Date:   Wed Jan 4 17:58:22 2023 +0000

    AP_HAL_ChibiOS: simple conversion tool for betaflight pin definitions

commit a72a5bcdf4ffca6c31f8c00eb9f1520bf8b253d4
Author: Andy Piper <github@andypiper.com>
Date:   Thu Jan 5 17:02:42 2023 +0000

    bootloaders: bootloader for FoxeerH743v1

commit b772d0e31cb214f9f9c5498dac6325271b293d45
Author: Andy Piper <github@andypiper.com>
Date:   Wed Jan 4 21:14:32 2023 +0000

    AP_HAL_ChibiOS: FoxeerH743 hwdef

commit 09ccedfd016d75658b80ec2cd1b3a2a7ab5ff2d7
Author: Andy Piper <github@andypiper.com>
Date:   Wed Jan 4 21:12:56 2023 +0000

    AP_Bootloader: add FoxeerH743v1 to board types

commit 1c34cd63905a41607940214418d51216a4f0ff4b
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Tue Jan 10 12:29:54 2023 +0000

    AP_Param: add shared Info defines

commit 7ff7d624890fccb59a19d6a4fa6987e8c32c651d
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Tue Jan 10 12:29:40 2023 +0000

    Tools: Replay: use shared Param info defines

commit d5c8fe4acab9204fe033faba8a192ecf971d7cf1
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Tue Jan 10 12:29:23 2023 +0000

    Tools: AP_Periph: use shared Param info defines

commit 3ac8ca65573b174379e766a89759cc72ef6c1952
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Wed Jan 4 01:39:14 2023 +0000

    Rover: use shared param info defines

commit 20b1622178caa00d2ea4f56e7dd37fd07c7a2763
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Wed Jan 4 01:39:14 2023 +0000

    Blimp: use shared param info defines

commit 8d963fab01b6e8ad9f32c6ce9d76599ed9e4997f
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Wed Jan 4 01:39:14 2023 +0000

    ArduSub: use shared param info defines

commit 09634e571223504e520c04524285ee9dfa7b5784
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Wed Jan 4 01:39:14 2023 +0000

    ArduPlane: use shared param info defines

commit 292a27aa98a4f6ad1a3664fd44a11afd608157e9
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Wed Jan 4 01:39:14 2023 +0000

    ArduCopter: use shared param info defines

commit b0da54c46f635545e18343faa9a5dc6a18288aa6
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Wed Jan 4 01:39:14 2023 +0000

    AntennaTracker: use shared param info defines

commit a7d8032e833eb9d3b85522d353753113e3e83c73
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Wed Jan 4 01:39:14 2023 +0000

    AP_Param: align param info structures to save flash

commit 5268b051fd5b999f08aab8cbbc708239dcd46f5f
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Wed Jan 4 01:39:14 2023 +0000

    AP_OSD: align param info structures to save flash

commit a1ad8e3a20c93af5a3c7f89177cba10724dbb3b3
Author: Iampete1 <iampete@hotmail.co.uk>
Date:   Wed Jan 4 01:39:14 2023 +0000

    AP_NMEA_Output: align param info structures to save flash

commit 35364964fcdadbaf44defd38fe2da5a515fe3dbf
Author: Peter Barker <pbarker@barker.dropbear.id.au>
Date:   Fri Jan 6 16:12:24 2023 +1100

    AP_Param: correct compilation when debugging enabled

    Correct passing through ov varargs from macro

commit 68fbdf11816eeb0574f817cde442d88db3d777a5
Author: MAD-CRAZY-MAN <awake_noh@naver.com>
Date:   Tue Jan 10 11:13:28 2023 +0900

    hwdef: update thepeach hwdef-bl.dat

commit 60f91506946d9c574bce406b678d143b8785ceec
Merge: 6e3357d2f4 08f652fe2c
Author: Sanket Sharma <sharma.sanket272@gmail.com>
Date:   Thu Jan 12 23:38:08 2023 +0530

    Merge branch 'master' into patch-8

commit 6e3357d2f4cd23b63e11d97c977ddfada691cfbc
Merge: ee54ee4bc7 9cb3bfbe05
Author: Sanket Sharma <sharma.sanket272@gmail.com>
Date:   Wed Jan 11 15:24:53 2023 +0530

    Merge branch 'master' into patch-8

commit ee54ee4bc79fb0544b95b5708cfb4390ebf89ee1
Merge: ac9ac8274d 37b54a7c9c
Author: Sanket Sharma <sharma.sanket272@gmail.com>
Date:   Wed Jan 11 13:06:48 2023 +0530

    Merge branch 'master' into patch-8

commit ac9ac8274d13eac5250e603654f8c793bf3139a4
Author: Sanket Sharma <sharma.sanket272@gmail.com>
Date:   Wed Jan 11 02:32:55 2023 +0530

    Tools: Updated ardupilot-ws and dependencies

    This PR will resolve all the dependency related issues with ardupilot_ros package. This package is tested with SwiftGust's and Khancyr's version of ardupilot_gazebo package for simulation purposes.
    Also updated the cartographer parameters  ArduPilot/ardupilot_ros#5  in response to this PR.
    Also I have added the script in comments to add packages.osrfoundation.org to the apt source to download gz-garden for ardupilot_gazebo.

    There's an issue found while downloading gz-garden. It tries to remove ROS and gazebo packages because of conflicting dependencies. Not sure if it's for all.