Tools: build_options.py: add missing dependencies
Fixing errors like this:

../../libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp: In member function 'virtual bool AP_PiccoloCAN_ESC::handle_can_frame(AP_HAL::CANFrame&)':
../../libraries/AP_PiccoloCAN/AP_PiccoloCAN_ESC.cpp:46:9: error: 'update_rpm' was not declared in this scope
   46 |         update_rpm(addr, rpm());
      |         ^~~~~~~~~~