AP_Param: fixed error: '__UINT16_MAX__' was not declared in this scope
instead of using the predefined __UINT16_MAX__ macro
(http://gcc.gnu.org/onlinedocs/cpp/Common-Predefined-Macros.html)

the appropriate UINT16_MAX from <stdint.h> is used (since there's no
std::numeric_limits).