Removed problematic merges
../../libraries/AP_Proximity/AP_Proximity_RPLidarA2.cpp:108:7: error: redefinition of ‘float AP_Proximity_RPLidarA2::distance_max() const’
 float AP_Proximity_RPLidarA2::distance_max() const
       ^~~~~~~~~~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.

../../libraries/AP_Proximity/AP_Proximity.cpp:28:10: fatal error: AP_Proximity_MorseSITL.h: No such file or directory
 #include "AP_Proximity_MorseSITL.h"
          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.

In AP_Proximity_RPlidarA2.cpp the removed part was redundant.

In AP_Proximity.cpp the removed #include did not exist. Removing for now.