AC_AttitudeControl: correct compilation failure on CubeOrange-heavy-periph
../../libraries/AC_AttitudeControl/AC_AttitudeControl.cpp:8:5: error: "APM_BUILD_TYPE" is not defined, evaluates to 0 [-Werror=undef]
    8 | #if APM_BUILD_TYPE(APM_BUILD_ArduPlane)
      |     ^~~~~~~~~~~~~~
compilation terminated due to -Wfatal-errors.
cc1plus: all warnings being treated as errors