AP_ExternalAHRS: fix Aeron PLX3 build with EXTERNALAHRS_BARO or COMPASS disabled
publish_sens_para() declared baro_ok and mag_ok unconditionally but only
used them inside the AP_BARO_EXTERNALAHRS_ENABLED and
AP_COMPASS_EXTERNALAHRS_ENABLED blocks. With either feature disabled the
variable is unused and -Werror=unused-variable fails the build:

  ./waf configure --board sitl --disable-EXTERNALAHRS_BARO && ./waf copter
  AP_ExternalAHRS_Aeron_plx.cpp:432:16: error: unused variable 'baro_ok'

Move each declaration inside the block that uses it. No behaviour change
with the default feature set.