AC_PID: re-order member declarations to avoid gcc-16 warning
  [  30/1360] Compiling libraries/AC_PID/AC_HELI_PID.cpp
  ../../libraries/AC_PID/AC_PID.cpp: In constructor ‘AC_PID::AC_PID(float, float, float, float, float, float, float, float, float, float, float)’:
  ../../libraries/AC_PID/AC_PID.cpp:114:40: error: ‘<unknown>’ may be used uninitialized [-Werror=maybe-uninitialized]
    114 |     default_slew_rate_max(initial_srmax)
        |                                        ^
  compilation terminated due to -Wfatal-errors.
  cc1plus: some warnings being treated as errors