AP_RAMTRON: correct compilation for gcc 9
../../libraries/AP_RAMTRON/AP_RAMTRON.cpp: In member function 'bool AP_RAMTRON::init()':
../../libraries/AP_RAMTRON/AP_RAMTRON.cpp:73:78: error: type qualifiers ignored on cast result type [-Werror=ignored-qualifiers]
   73 |             cypress_rdid const * const cypress = (cypress_rdid const * const)rdid;
      |                                                                              ^~~~
compilation terminated due to -Wfatal-errors.
cc1plus: some warnings being treated as errors

This also has the benefit of only reading the expected number of bytes
from the device.