AP_Bootloader: avoid compilation error with -Werror=type-limits
See https://github.com/ArduPilot/ardupilot/issues/14596

I am getting this error while building the bootloader for mRoControlZeroF7 device. Please help me.

[81/85] Linking build/mRoControlZeroF7/Tools/AP_Bootloader/liblibcanard.a
../../Tools/AP_Bootloader/support.cpp: In function 'void flash_init()':
../../Tools/AP_Bootloader/support.cpp:95:21: error: comparison of unsigned expression < 0 is always false [-Werror=type-limits]
while (reserved < FLASH_RESERVE_END_KB * 1024U) {
^
compilation terminated due to -Wfatal-errors.