Tools: scripts: Update jsbsim installation script.
According to http://ardupilot.org/dev/docs/setting-up-sitl-on-linux.html

"
In the past ArduPilot required a special version of JSBSim. As of December 2018 that is no longer the case, and we can use the standard JSBSim releases.
"

Moreover currently build-jsbsim.sh is failing with error:

../../src/models/propulsion/FGTurbine.h:297:3: error: ‘FGParameter’ does not name a type; did you mean ‘FGThruster’?
   FGParameter *N1SpoolUp;
   ^~~~~~~~~~~